---- ATUALIZA A TABELA DE PROJETO COM O COMITE RESPONSÁVEL.
SET SERVEROUTPUT ON;
BEGIN
FOR I IN(SELECT DISTINCT CAAE.CO_PROJETO, CAAE.CO_COMITE_ETICA
          FROM DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE CAAE,
              (SELECT MAX(DT_ESTADO) DT_ESTADO, CO_PROJETO 
                FROM DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE 
                GROUP BY CO_PROJETO
               )ULTIMA_APRECIACAO
          WHERE ULTIMA_APRECIACAO.DT_ESTADO = CAAE.DT_ESTADO
          AND CAAE.CO_PROJETO = ULTIMA_APRECIACAO.CO_PROJETO
          AND CAAE.CO_COMITE_ETICA NOT IN(8, 8000)
          AND EXISTS(SELECT 1 FROM DBPLATAFORMABR.TB_PROJETO P WHERE P.CO_SEQ_PROJETO = CAAE.CO_PROJETO AND P.CO_COMITE_ETICA IS NULL)
    )LOOP
        UPDATE DBPLATAFORMABR.TB_PROJETO SET CO_COMITE_ETICA = I.CO_COMITE_ETICA WHERE CO_SEQ_PROJETO = I.CO_PROJETO AND CO_COMITE_ETICA IS NULL;
        DBMS_OUTPUT.PUT_LINE('PROJETO = '||I.CO_PROJETO||' COMITÊ DE ÉTICA RESPONSÁVEL = '||I.CO_COMITE_ETICA);
    END LOOP;
END;
/

----------------------------------------------------------------------------------------------------------------------------------------------------


---- PARA CONEP - ATUALIZA A TABELA DE PROJETO COM O COMITE RESPONSÁVEL.
SET SERVEROUTPUT ON;
BEGIN
FOR I IN(SELECT DISTINCT CAAE.CO_PROJETO, CAAE.CO_COMITE_ETICA
          FROM DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE CAAE,
              (SELECT MAX(DT_ESTADO) DT_ESTADO, CO_PROJETO 
                FROM DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE 
                GROUP BY CO_PROJETO
               )ULTIMA_APRECIACAO
          WHERE ULTIMA_APRECIACAO.DT_ESTADO = CAAE.DT_ESTADO
          AND CAAE.CO_PROJETO = ULTIMA_APRECIACAO.CO_PROJETO
          AND CAAE.CO_COMITE_ETICA = 8
          AND (SELECT COUNT(*) FROM DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE C2 WHERE CO_PROJETO = CAAE.CO_PROJETO AND C2.CO_COMITE_ETICA != 8)=0
          AND EXISTS(SELECT 1 FROM DBPLATAFORMABR.TB_PROJETO P WHERE P.CO_SEQ_PROJETO = CAAE.CO_PROJETO AND P.CO_COMITE_ETICA IS NULL)
    )LOOP
        UPDATE DBPLATAFORMABR.TB_PROJETO SET CO_COMITE_ETICA = I.CO_COMITE_ETICA WHERE CO_SEQ_PROJETO = I.CO_PROJETO AND CO_COMITE_ETICA IS NULL;
        DBMS_OUTPUT.PUT_LINE('PROJETO = '||I.CO_PROJETO||' COMITÊ DE ÉTICA RESPONSÁVEL = '||I.CO_COMITE_ETICA);
    END LOOP;
END;
/


SELECT CO_SEQ_PROJETO, CO_COMITE_ETICA, CO_TIPO_SITUACAO_PROJETO FROM DBPLATAFORMABR.TB_PROJETO WHERE CO_SEQ_PROJETO = 155366;
SELECT * FROM DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE WHERE CO_PROJETO = 155366 ORDER BY DT_ESTADO;



SELECT *
    FROM DBPLATAFORMABR.TB_PARECER RELATOR
    INNER JOIN DBPLATAFORMABR.TB_APRECIACAO_CERTIFICADO_CAAE CAAE
    ON
     CAAE.CO_PROJETO          = RELATOR.CO_PROJETO
    AND CAAE.NU_VERSAO             = RELATOR.NU_VERSAO
    AND CAAE.NU_DIGITO_VERIFICADOR = RELATOR.NU_DIGITO_VERIFICADOR
    AND CAAE.TP_CENTRO_PESQUISA    = RELATOR.TP_CENTRO
    AND CAAE.NU_ANO_SUBMISSAO      = RELATOR.NU_ANO_SUBMISSAO
    AND CAAE.NU_GESTAO             = RELATOR.NU_SEQ_GESTAO
    AND CAAE.CO_COMITE_ETICA       = RELATOR.CO_COMITE_ETICA
    AND RELATOR.TP_PARECER         = 'R'
    AND RELATOR.ST_REGISTRO_ATIVO  = 'S'
    
    WHERE CAAE.CO_PROJETO = 57573;
